
SELECT id_categoria, id_produto FROM nk_tb_categoria_produto WHERE id_categoria = 1;

SELECT NR_PRECO, NM_PRODUTO FROM NK_TB_PRODUTO ORDER BY NR_PRECO ASC;


-- GROUP BY

SELECT NK_TB_USUARIO.nm_usuario AS nm_usuario, NK_TB_PRODUTO.nm_produto, COUNT(*) AS QUANTIDADE
FROM NK_TB_CARRINHO
INNER JOIN NK_TB_USUARIO ON NK_TB_CARRINHO.id_usuario = NK_TB_USUARIO.id_usuario
INNER JOIN NK_TB_PRODUTO ON NK_TB_CARRINHO.id_produto = NK_TB_PRODUTO.id_produto
GROUP BY NK_TB_USUARIO.nm_usuario, NK_TB_PRODUTO.nm_produto;

-- INNER JOIN

SELECT NK_TB_USUARIO.*, NK_TB_CARRINHO.*, NK_TB_PRODUTO.*
FROM NK_TB_USUARIO
INNER JOIN NK_TB_CARRINHO ON NK_TB_USUARIO.id_usuario = NK_TB_CARRINHO.id_usuario
INNER JOIN NK_TB_PRODUTO ON NK_TB_CARRINHO.id_produto = NK_TB_PRODUTO.id_produto;


